### ISSUE TITLE
Develop detailed instructions for setting up kubernetes cluster for running these tests

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-integration-tests#4]
As described by @nbren12 in https://github.com/pangeo-data/pangeo-integration-tests/issues/1#issuecomment-839063503, we will run these tests as a cron job in a kubernetes cluster. Something like this:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  generateName: pangeo-integration-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: accountWithNeededPrivs
          containers:
          - name: hello
            image: pangeo-integration-test:latest
            imagePullPolicy: IfNotPresent
            # all logic happens here
            # and publishes a integration report to a static webpage
            command: ["/bin/bash", "run_tests.sh"]

          restartPolicy: OnFailure
```

How should this kubernetes cluster be configured? How does one set up such a cluster from scratch on AWS, GCloud, and Azure? Could we use terraform? Can we run it in existing Pangeo clusters?

The easier we can make this step, the easier it will be to get different testing environments set up.
